#!/usr/bin/env python3

import sys, argparse, os
from os.path import join as pjoin

import numpy as np

import qeschema # read Quantum Espresso XML output

from ase.io import read as ase_read # read geometry from qe input file
from ase.units import Hartree, Bohr # conversion factors


def qestruct2ase(xml_atomic_structure):
    """Convert the structure from QE XML output file to ASE Atoms object"""

    from ase import Atom, Atoms
    from ase.units import Bohr

    c_cell = Bohr*np.array(list(xml_atomic_structure['cell'].values()))
    c_geom = Atoms([Atom(i['@name'], position=Bohr*np.array(i['$']), index=i['@index'])
                    for i in xml_atomic_structure['atomic_positions']['atom']],
                   cell=c_cell, pbc=[True, True, True])
    return c_geom



def compute_freq(indices, displ, geom, infile, indir, qeout, outdir, debug):
    """Create dynamical matrix from DFT data (QE xml output).
    Diagonalise it.
    Return eigeval (in Eh/(Da*a0^2)), eigenvectors (columns of matrix), and frequncies (eigval in THz)."""

    print('displacement %f [Ang]' %  displ, end=' ')
    displ /= Bohr # convert to units of QE XML output
    print('%f [a0]' % displ)

    # atomic units with mass in Da (unified atomic mass unit m(12C)=12 Da)
    conv2THz = 968.2886664991329/(2*np.pi)  # omega in 2*pi/(time in atomoc units) to frequency in THz
    THz2cminv = 33.356683 # 1 THz in cm^-1
    hbar = 6.582119568038699e-4 # eV/THz

    coord_label = ['x', 'y', 'z'] # shortcut for printing


    N = len(indices)
    masses = geom.get_masses()[indices]

    print('consider %i atoms at indices' % N, ' '.join(['%i (%s)' % (i, geom[i].symbol) for i in indices]))
    print('masses',  ' '.join(['%s: %.3g [Da]' % (a.symbol, m) for m,a in zip(masses, geom[indices])]))

    # init 3Nx3N matrices of forces
    # one for positive and one for negative displacements
    forceMatr_pos = np.zeros((3*N, 3*N))
    forceMatr_neg = np.zeros((3*N, 3*N))
    print('Force matrix shape', forceMatr_neg.shape)

    ib = 0 # index for displaced atoms
    for ii, atm in enumerate(geom): # run on all atoms

        # skip atom if not in selected indices
        if ii not in indices: continue

        for j in range(3): # x y z

            imtr = ib*3+j # index of force matrix
            print('Load displ atom %i (%s) along %s (mtr row %i)' % (ii, geom[ii].symbol, coord_label[j], imtr))

            # --- positive displ
            # --- --- read QE output (tree generated by generate_conf.py)
            c_dir  = 'dpos_%i_%i' % (ii, j)
            qe = qeschema.PwDocument(pjoin(indir, c_dir, qeout)).to_dict(validation='lax')['qes:espresso']

            # --- --- check displacement is right
            c_geom = qestruct2ase(qe['output']['atomic_structure']) # [Ang]
            if not np.isclose((c_geom.positions-geom.positions)[ii, j]/Bohr, displ):
                raise RuntimeError('Wrong displacement (current-original)[atom_i, coord_j] != displ: ', (c_geom.positions-geom.positions)[ii, j]/Bohr,  displ)

            # --- --- read forces
            dim = list(reversed(qe['output']['forces']['@dims'])) # QE saves with different ordering than numpy
            forces = np.array(qe['output']['forces']['$']).reshape(dim) # Hartree/Bohr

            # --- --- assign force matrix entry
            for ic, n in enumerate(indices):
                for g in range(3):
                    jmtr = ic*3+g
                    if debug: print('+ force on %i coord %s pos (matr ind %i,%i): %9.3g Eh/a0' % (n, coord_label[g], imtr, jmtr, 2*forces[n,g]))
                    forceMatr_pos[imtr, jmtr] = forces[n,g] # Hartree/Bohr

            # --- negative displ
            c_dir  = 'dneg_%i_%i' % (ii, j)
            qe = qeschema.PwDocument(pjoin(indir, c_dir, qeout)).to_dict(validation='lax')['qes:espresso']

            c_geom = qestruct2ase(qe['output']['atomic_structure']) # [Ang]
            if not np.isclose((c_geom.positions-geom.positions)[ii, j]/Bohr, -displ):
                raise RuntimeError('Wrong displacement (current-original)[atom_i, coord_j] != displ: ', (c_geom.positions-geom.positions)[ii, j]/Bohr,  displ)

            dim = list(reversed(qe['output']['forces']['@dims']))
            forces = np.array(qe['output']['forces']['$']).reshape(dim)  # Hartree/Bohr

            for ic, n in enumerate(indices):
                for g in range(3):
                    jmtr = ic*3+g
                    if debug: print('- force on %i coord %s pos (matr ind %i,%i): %9.3g Eh/a0' % (n, coord_label[g], imtr, jmtr, 2*forces[n,g]))
                    forceMatr_neg[imtr, jmtr] = forces[n,g]  # Hartree/Bohr

            if debug: print('-'*20)
        ib += 1 # increas displace atoms count
    print()

    # print and save forces
    if debug:
        print('F(positive displ) [Eh/a0]')
        print(forceMatr_pos)
        print('F(negative displ) [Eh/a0]')
        print(forceMatr_neg)
    np.savetxt(pjoin(outdir, 'force_posdx.dat'), forceMatr_pos, fmt='%25.15g', header='Eh/a0')
    np.savetxt(pjoin(outdir, 'force_negdx.dat'), forceMatr_neg, fmt='%25.15g', header='Eh/a0')

    # compute force constant from finite difference
    forceMatr = -(forceMatr_pos - forceMatr_neg)/(2*displ)  # Hartree/Bohr^2
    if debug:
        print('force constants [Eh/a0^2]')
        np.set_printoptions(precision=3)
        print(forceMatr)
    np.savetxt(pjoin(outdir, 'force_const.dat'), forceMatr, fmt='%25.15g', header='Eh/a0^2')

    # build dynamic matrix
    dynaMatr = np.zeros(forceMatr.shape)
    for ii in range(len(indices)):
        for j in range(3):
            imtr = ii*3+j
            for n in range(len(indices)):
                for g in range(3):
                    jmtr = n*3+g
                    dynaMatr[imtr, jmtr]= forceMatr[imtr,jmtr]/np.sqrt(masses[ii]*masses[n]) # Hartree/(Bohr^2*Da)
                    # symmetrise it. Would not recommend
                    #dynaMatr[imtr, jmtr]= (forceMatr[imtr,jmtr]+forceMatr[jmtr,imtr])/(2*np.sqrt(masses[ii]*masses[n])) # Hartree/(Bohr^2*Da)

    if debug:
        print('dynamical matrix [Eh/(a0^2 Da)]')
        np.set_printoptions(precision=3) # pretty print
        print(dynaMatr)
        print()
    np.savetxt(pjoin(outdir, 'dyna_matr.dat'), dynaMatr, fmt='%25.15g', header='Eh/(a0^2 Da)')

    # compute diagonalisation
    print('Diagonalising...')
    eigval, eigvec = np.linalg.eig(dynaMatr)
    print()

    print('Ordered results:')
    if debug:
        print('eigval')
        print(eigval)
        print('eigvect')
        print(eigvec)

    # check and handle numerical quirks
    thold = 1e-16
    for ii, i in enumerate(eigval):
        if np.imag(i) >thold: print('!'*10, 'Eigen not real', i, 'discard imag')
    eigval = eigval.astype(float)
    for ii, i in enumerate(eigval):
        if i <thold: print('!'*10, 'Eigen NEGATIVE:', i)
    # is there a way to deal with this properly? The problem is in DFT calc, but we should signal it correctly
    #eigval[eigval<-thold] *= -1 # reverse negative
    #eigval[eigval<-thold] = 0 # reverse negative
    #eigval[np.abs(eigval)<thold] = 0 # avoid nan

    # sort eigenvalues in ascending order
    eigsort = np.argsort(eigval)
    eigval = eigval[eigsort]
    eigvec = eigvec[:,eigsort] # sort eigenvectors
    omegas = np.array([np.sqrt(e) if e>0 else -np.sqrt(-e) for e in eigval]) # D@eigv = omega^2 * eigv
    #omegas = np.array([np.sqrt(e) if e>0 else np.sqrt(-e) for e in eigval]) # D@eigv = omega^2 * eigv

    # print and save
    print('         '+' '*15, ' '.join(['     l%-4s' % ie for ie in range(eigval.shape[0])]))
    print('eigenvals %-15s' % '[Eh/(Da*a0^2)]',  ' '.join(['%10.4f' % e for e in eigval]))
    print('freq      %-15s' % '[THz]',  ' '.join(['%10.4f' % e for e in omegas*conv2THz]))
    print('freq      %-15s' % '[cm^-1]',' '.join(['%10.4f' % e for e in omegas*conv2THz*THz2cminv]))

    KBT = 0.025 # eV
    ZPEs = np.zeros(len(omegas))
    Evibs = np.zeros(len(omegas))
    TSs = np.zeros(len(omegas))
    Avibs = np.zeros(len(omegas))
    for io, omega in enumerate(omegas):
        omega = omega*2*np.pi*conv2THz # cancel the 2pi in conv2THz
        # how to handle this properly? Using nan maybe?
        if omega <= 0: 
            print('!!! omega(%i)<0 !!!' % io, file=sys.stderr, end=' ')
            #raise RuntimeError('this should not happen omega<0')
            # pick one 
            print('skip', file=sys.stderr, flush=True); continue  # skip it
            #print('change sign', file=sys.stderr, flush=True) ; omega*=-1 # canghe sign to it
        #Evibs[io] = omega*hbar/2 + hbar*omega/(np.exp(np.exp(omega*hbar/KBT))-1)
        Evibs[io] = omega*hbar/2 + hbar*omega/(np.exp(omega*hbar/KBT)-1)
        Avibs[io] = omega*hbar/2 + KBT*np.log(1-np.exp(-omega*hbar/KBT))
        #TSs[io]   = hbar*omega/(np.exp(np.exp(omega*hbar/KBT))-1) - KBT*np.log(1- np.exp(-omega*hbar/KBT))
        TSs[io]   = hbar*omega/(np.exp(omega*hbar/KBT)-1) - KBT*np.log(1-np.exp(-omega*hbar/KBT))
        ZPEs[io]  = omega*hbar/2

        # debug: check we are doing separate terms and sum correctly
        #print(np.isclose(Evibs[io]-TSs[io], Avibs[io]), Evibs[io]-TSs[io], Avibs[io])

    print('Evib        %-15s' % '[eV]',   ' '.join(['%10.4f' % e for e in Evibs]),
          'sum: %10.4g' % np.sum(Evibs))
    print('TS(Troom)   %-15s' % '[eV]', ' '.join(['%10.4f' % e for e in TSs]),
          'sum: %10.4g' % np.sum(TSs))
    print('ZPE         %-15s' % '[eV]',   ' '.join(['%10.4f' % e for e in ZPEs]),
          'sum: %10.4g' % np.sum(ZPEs))
    print('Avib(Troom) %-15s' % '[eV]', ' '.join(['%10.4f' % e for e in Avibs]),
          'sum: %10.4g' % np.sum(Avibs))

    with open(pjoin(outdir, 'eigenvalues.dat'), 'w') as outf:
        print('#%-24s ' % 'eig[Eh/(Da*a0^2)]'+ ' '.join(['%-25s' % s
                                                         for s in ['freq[THz]',
                                                                   'freq[cm^-1]',
                                                                   'ZPE[eV]',
                                                                   'TroomS[eV]',
                                                                   'Avib(Troom)[eV]'
                                                                   ]]),
              file=outf)
        for ii, (omega, eig) in enumerate(zip(omegas, eigval)):
            print(' '.join(['%-25.15g' % s for s in [eig,
                                                     omega*conv2THz,
                                                     omega*conv2THz*THz2cminv,
                                                     ZPEs[ii],
                                                     TSs[ii],
                                                     Avibs[ii]
                                                     ]]),
                  file=outf)

    print('eigvects:')

    print(' '*7+' '.join([' v%-3s' % i for i in range(eigvec.shape[0])]))
    for ir in range(eigvec.shape[0]):
        if (ir%3) == 0: print(' '*6,'-'*6*(eigvec.shape[0]))
        print('%3s_%s:' % (geom[indices[int(ir/3)]].symbol, coord_label[ir%3]), ' '.join(['%5.2f' % f for f in eigvec[ir]]))

    np.savetxt(pjoin(outdir, 'eigenvectors.dat'), eigvec, fmt='%10.5f', header='unitary eigenvectors (columns). Eigevnal: %s' % str(eigval))

    return eigval, eigvec, omegas*conv2THz

if __name__ == "__main__":

    # --- argument parser
    parser = argparse.ArgumentParser(description="Collect QuantumEspresso output from finite displacement and diagonalize dyncamical matrix at Gamma for Zero Point Energy evaluation.",
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    # --- --- positional arguments
    parser.add_argument('indices',
                        type=int, nargs='+',
                        help='indices of atoms displaced')
    # --- --- optional args
    parser.add_argument('--qeout',
                        type=str, default='pwscf.xml',
                        help='name of QE XML output. Must be the same for all displacement runs.')
    parser.add_argument('--outdir',
                        type=str, default='./',
                        help='directory for saving files.')
    parser.add_argument('-d', '--displ',
                        type=float, default=0.01,
                        help='displacement used in finite difference [Ang]')
    parser.add_argument('-f', '--filename',
                        type=str, default='pw.in',
                        help='QE input file (for masses and displacement check)')
    parser.add_argument('--debug',
                        action='store_true', help='print debug informations')
    # --- --- init
    args = parser.parse_args(sys.argv[1:])

    infile = args.filename # QE input file with starting structure
    qeout = args.qeout     # XML output of QE ! must be the same for all displacements!
    outdir = args.outdir   # where to save results
    if not os.path.exists(outdir): os.makedirs(outdir) # if not already there, create (with intermediaries)
    debug = args.debug

    # displacement from equilibrium structure
    displ = args.displ # Ang

    geom = ase_read(infile, format='espresso-in')

    # which atoms have been displaced
    indices = args.indices

    compute_freq(indices, displ, geom, infile, outdir, qeout, outdir, debug)
